pipeline:
  name: vishal-sample-pl-1
  identifier: vishal-sample-pl-1
  projectIdentifier: Krishika_CD_Samples
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: tmp-stage
        identifier: deployownapp
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: vishalt2
          environment:
            environmentRef: vishalsamplepipeline
            deployToAll: false
            infrastructureDefinitions:
              - identifier: vishalterraforminfra
          execution:
            steps:
              - step:
                  name: Stage Deployment
                  identifier: stageDeployment
                  type: K8sBlueGreenDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
